"""
Static Architecture Data for Pretrained Models

Pre-computed layer definitions for all 7 supported pretrained models.
Returns instant responses without loading model weights — critical for
free-tier hosting where weight downloads would timeout.

Data matches torchvision model structures exactly (verified offline).
Shapes follow PyTorch convention: [C, H, W] for feature maps.
"""

from typing import Any, Dict

from .alexnet import _alexnet
from .efficientnet import _efficientnet_b0
from .mobilenet import _mobilenet_v2
from .resnet import _resnet50
from .transformers import _bert_base, _gpt2
from .vgg import _vgg16

# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

_BUILDERS = {
    "alexnet": _alexnet,
    "vgg16": _vgg16,
    "resnet50": _resnet50,
    "mobilenet_v2": _mobilenet_v2,
    "efficientnet_b0": _efficientnet_b0,
    "bert_base": _bert_base,
    "gpt2": _gpt2,
}


def get_static_architecture(model_id: str) -> Dict[str, Any] | None:
    """
    Return pre-computed architecture data for a pretrained model.
    Returns None if no static data is available (e.g. custom uploaded models).
    """
    builder = _BUILDERS.get(model_id)
    if builder is None:
        return None
    return builder()


def has_static_architecture(model_id: str) -> bool:
    """Check if static architecture data is available for a model."""
    return model_id in _BUILDERS


# ─────────────────────────────────────────────────────────────────────────────
# Static layer lists (for /layers endpoint — Grad-CAM target selection)
# Extracted offline from torchvision models via model.named_modules()
# ─────────────────────────────────────────────────────────────────────────────

_STATIC_LAYERS: Dict[str, Dict[str, Any]] = {
    "alexnet": {
        "all_layers": [
            "features",
            "features.0",
            "features.1",
            "features.2",
            "features.3",
            "features.4",
            "features.5",
            "features.6",
            "features.7",
            "features.8",
            "features.9",
            "features.10",
            "features.11",
            "features.12",
            "avgpool",
            "classifier",
            "classifier.0",
            "classifier.1",
            "classifier.2",
            "classifier.3",
            "classifier.4",
            "classifier.5",
            "classifier.6",
        ],
        "conv_layers": [
            "features.0",
            "features.3",
            "features.6",
            "features.8",
            "features.10",
        ],
        "default_target_layer": "features.10",
    },
    "vgg16": {
        "all_layers": [
            "features",
            "features.0",
            "features.1",
            "features.2",
            "features.3",
            "features.4",
            "features.5",
            "features.6",
            "features.7",
            "features.8",
            "features.9",
            "features.10",
            "features.11",
            "features.12",
            "features.13",
            "features.14",
            "features.15",
            "features.16",
            "features.17",
            "features.18",
            "features.19",
            "features.20",
            "features.21",
            "features.22",
            "features.23",
            "features.24",
            "features.25",
            "features.26",
            "features.27",
            "features.28",
            "features.29",
            "features.30",
            "avgpool",
            "classifier",
            "classifier.0",
            "classifier.1",
            "classifier.2",
            "classifier.3",
            "classifier.4",
            "classifier.5",
            "classifier.6",
        ],
        "conv_layers": [
            "features.0",
            "features.2",
            "features.5",
            "features.7",
            "features.10",
            "features.12",
            "features.14",
            "features.17",
            "features.19",
            "features.21",
            "features.24",
            "features.26",
            "features.28",
        ],
        "default_target_layer": "features.28",
    },
    "resnet50": {
        "all_layers": [
            "conv1",
            "bn1",
            "relu",
            "maxpool",
            "layer1",
            "layer1.0",
            "layer1.0.conv1",
            "layer1.0.bn1",
            "layer1.0.relu",
            "layer1.0.conv2",
            "layer1.0.bn2",
            "layer1.0.conv3",
            "layer1.0.bn3",
            "layer1.0.downsample",
            "layer1.0.downsample.0",
            "layer1.0.downsample.1",
            "layer1.1",
            "layer1.1.conv1",
            "layer1.1.bn1",
            "layer1.1.relu",
            "layer1.1.conv2",
            "layer1.1.bn2",
            "layer1.1.conv3",
            "layer1.1.bn3",
            "layer1.2",
            "layer1.2.conv1",
            "layer1.2.bn1",
            "layer1.2.relu",
            "layer1.2.conv2",
            "layer1.2.bn2",
            "layer1.2.conv3",
            "layer1.2.bn3",
            "layer2",
            "layer2.0",
            "layer2.0.conv1",
            "layer2.0.bn1",
            "layer2.0.relu",
            "layer2.0.conv2",
            "layer2.0.bn2",
            "layer2.0.conv3",
            "layer2.0.bn3",
            "layer2.0.downsample",
            "layer2.0.downsample.0",
            "layer2.0.downsample.1",
            "layer2.1",
            "layer2.1.conv1",
            "layer2.1.bn1",
            "layer2.1.relu",
            "layer2.1.conv2",
            "layer2.1.bn2",
            "layer2.1.conv3",
            "layer2.1.bn3",
            "layer2.2",
            "layer2.2.conv1",
            "layer2.2.bn1",
            "layer2.2.relu",
            "layer2.2.conv2",
            "layer2.2.bn2",
            "layer2.2.conv3",
            "layer2.2.bn3",
            "layer2.3",
            "layer2.3.conv1",
            "layer2.3.bn1",
            "layer2.3.relu",
            "layer2.3.conv2",
            "layer2.3.bn2",
            "layer2.3.conv3",
            "layer2.3.bn3",
            "layer3",
            "layer3.0",
            "layer3.0.conv1",
            "layer3.0.bn1",
            "layer3.0.relu",
            "layer3.0.conv2",
            "layer3.0.bn2",
            "layer3.0.conv3",
            "layer3.0.bn3",
            "layer3.0.downsample",
            "layer3.0.downsample.0",
            "layer3.0.downsample.1",
            "layer3.1",
            "layer3.1.conv1",
            "layer3.1.bn1",
            "layer3.1.relu",
            "layer3.1.conv2",
            "layer3.1.bn2",
            "layer3.1.conv3",
            "layer3.1.bn3",
            "layer3.2",
            "layer3.2.conv1",
            "layer3.2.bn1",
            "layer3.2.relu",
            "layer3.2.conv2",
            "layer3.2.bn2",
            "layer3.2.conv3",
            "layer3.2.bn3",
            "layer3.3",
            "layer3.3.conv1",
            "layer3.3.bn1",
            "layer3.3.relu",
            "layer3.3.conv2",
            "layer3.3.bn2",
            "layer3.3.conv3",
            "layer3.3.bn3",
            "layer3.4",
            "layer3.4.conv1",
            "layer3.4.bn1",
            "layer3.4.relu",
            "layer3.4.conv2",
            "layer3.4.bn2",
            "layer3.4.conv3",
            "layer3.4.bn3",
            "layer3.5",
            "layer3.5.conv1",
            "layer3.5.bn1",
            "layer3.5.relu",
            "layer3.5.conv2",
            "layer3.5.bn2",
            "layer3.5.conv3",
            "layer3.5.bn3",
            "layer4",
            "layer4.0",
            "layer4.0.conv1",
            "layer4.0.bn1",
            "layer4.0.relu",
            "layer4.0.conv2",
            "layer4.0.bn2",
            "layer4.0.conv3",
            "layer4.0.bn3",
            "layer4.0.downsample",
            "layer4.0.downsample.0",
            "layer4.0.downsample.1",
            "layer4.1",
            "layer4.1.conv1",
            "layer4.1.bn1",
            "layer4.1.relu",
            "layer4.1.conv2",
            "layer4.1.bn2",
            "layer4.1.conv3",
            "layer4.1.bn3",
            "layer4.2",
            "layer4.2.conv1",
            "layer4.2.bn1",
            "layer4.2.relu",
            "layer4.2.conv2",
            "layer4.2.bn2",
            "layer4.2.conv3",
            "layer4.2.bn3",
            "avgpool",
            "fc",
        ],
        "conv_layers": [
            "conv1",
            "layer1.0.conv1",
            "layer1.0.conv2",
            "layer1.0.conv3",
            "layer1.0.downsample.0",
            "layer1.1.conv1",
            "layer1.1.conv2",
            "layer1.1.conv3",
            "layer1.2.conv1",
            "layer1.2.conv2",
            "layer1.2.conv3",
            "layer2.0.conv1",
            "layer2.0.conv2",
            "layer2.0.conv3",
            "layer2.0.downsample.0",
            "layer2.1.conv1",
            "layer2.1.conv2",
            "layer2.1.conv3",
            "layer2.2.conv1",
            "layer2.2.conv2",
            "layer2.2.conv3",
            "layer2.3.conv1",
            "layer2.3.conv2",
            "layer2.3.conv3",
            "layer3.0.conv1",
            "layer3.0.conv2",
            "layer3.0.conv3",
            "layer3.0.downsample.0",
            "layer3.1.conv1",
            "layer3.1.conv2",
            "layer3.1.conv3",
            "layer3.2.conv1",
            "layer3.2.conv2",
            "layer3.2.conv3",
            "layer3.3.conv1",
            "layer3.3.conv2",
            "layer3.3.conv3",
            "layer3.4.conv1",
            "layer3.4.conv2",
            "layer3.4.conv3",
            "layer3.5.conv1",
            "layer3.5.conv2",
            "layer3.5.conv3",
            "layer4.0.conv1",
            "layer4.0.conv2",
            "layer4.0.conv3",
            "layer4.0.downsample.0",
            "layer4.1.conv1",
            "layer4.1.conv2",
            "layer4.1.conv3",
            "layer4.2.conv1",
            "layer4.2.conv2",
            "layer4.2.conv3",
        ],
        "default_target_layer": "layer4.2.conv3",
    },
    "mobilenet_v2": {
        "all_layers": [
            "features",
            "features.0",
            "features.0.0",
            "features.0.1",
            "features.0.2",
            "features.1",
            "features.1.conv",
            "features.1.conv.0",
            "features.1.conv.0.0",
            "features.1.conv.0.1",
            "features.1.conv.0.2",
            "features.1.conv.1",
            "features.1.conv.2",
            "features.2",
            "features.2.conv",
            "features.2.conv.0",
            "features.2.conv.0.0",
            "features.2.conv.0.1",
            "features.2.conv.0.2",
            "features.2.conv.1",
            "features.2.conv.1.0",
            "features.2.conv.1.1",
            "features.2.conv.1.2",
            "features.2.conv.2",
            "features.2.conv.3",
            "features.3",
            "features.4",
            "features.5",
            "features.6",
            "features.7",
            "features.8",
            "features.9",
            "features.10",
            "features.11",
            "features.12",
            "features.13",
            "features.14",
            "features.15",
            "features.16",
            "features.17",
            "features.18",
            "features.18.0",
            "features.18.1",
            "features.18.2",
            "classifier",
            "classifier.0",
            "classifier.1",
        ],
        "conv_layers": [
            "features.0.0",
            "features.1.conv.0.0",
            "features.1.conv.1",
            "features.2.conv.0.0",
            "features.2.conv.1.0",
            "features.2.conv.2",
            "features.3.conv.0.0",
            "features.3.conv.1.0",
            "features.3.conv.2",
            "features.4.conv.0.0",
            "features.4.conv.1.0",
            "features.4.conv.2",
            "features.5.conv.0.0",
            "features.5.conv.1.0",
            "features.5.conv.2",
            "features.6.conv.0.0",
            "features.6.conv.1.0",
            "features.6.conv.2",
            "features.7.conv.0.0",
            "features.7.conv.1.0",
            "features.7.conv.2",
            "features.8.conv.0.0",
            "features.8.conv.1.0",
            "features.8.conv.2",
            "features.9.conv.0.0",
            "features.9.conv.1.0",
            "features.9.conv.2",
            "features.10.conv.0.0",
            "features.10.conv.1.0",
            "features.10.conv.2",
            "features.11.conv.0.0",
            "features.11.conv.1.0",
            "features.11.conv.2",
            "features.12.conv.0.0",
            "features.12.conv.1.0",
            "features.12.conv.2",
            "features.13.conv.0.0",
            "features.13.conv.1.0",
            "features.13.conv.2",
            "features.14.conv.0.0",
            "features.14.conv.1.0",
            "features.14.conv.2",
            "features.15.conv.0.0",
            "features.15.conv.1.0",
            "features.15.conv.2",
            "features.16.conv.0.0",
            "features.16.conv.1.0",
            "features.16.conv.2",
            "features.17.conv.0.0",
            "features.17.conv.1.0",
            "features.17.conv.2",
            "features.18.0",
        ],
        "default_target_layer": "features.18.0",
    },
    "efficientnet_b0": {
        "all_layers": [
            "features",
            "features.0",
            "features.0.0",
            "features.0.1",
            "features.0.2",
            "features.1",
            "features.1.0",
            "features.2",
            "features.2.0",
            "features.2.1",
            "features.3",
            "features.3.0",
            "features.3.1",
            "features.4",
            "features.4.0",
            "features.4.1",
            "features.4.2",
            "features.5",
            "features.5.0",
            "features.5.1",
            "features.5.2",
            "features.6",
            "features.6.0",
            "features.6.1",
            "features.6.2",
            "features.6.3",
            "features.7",
            "features.7.0",
            "features.8",
            "features.8.0",
            "features.8.1",
            "features.8.2",
            "avgpool",
            "classifier",
            "classifier.0",
            "classifier.1",
        ],
        "conv_layers": [
            "features.0.0",
            "features.1.0.block.0.0",
            "features.1.0.block.1.0",
            "features.2.0.block.0.0",
            "features.2.0.block.1.0",
            "features.2.1.block.0.0",
            "features.2.1.block.1.0",
            "features.3.0.block.0.0",
            "features.3.0.block.1.0",
            "features.3.1.block.0.0",
            "features.3.1.block.1.0",
            "features.4.0.block.0.0",
            "features.4.0.block.1.0",
            "features.4.1.block.0.0",
            "features.4.1.block.1.0",
            "features.4.2.block.0.0",
            "features.4.2.block.1.0",
            "features.5.0.block.0.0",
            "features.5.0.block.1.0",
            "features.5.1.block.0.0",
            "features.5.1.block.1.0",
            "features.5.2.block.0.0",
            "features.5.2.block.1.0",
            "features.6.0.block.0.0",
            "features.6.0.block.1.0",
            "features.6.1.block.0.0",
            "features.6.1.block.1.0",
            "features.6.2.block.0.0",
            "features.6.2.block.1.0",
            "features.6.3.block.0.0",
            "features.6.3.block.1.0",
            "features.7.0.block.0.0",
            "features.7.0.block.1.0",
            "features.8.0",
        ],
        "default_target_layer": "features.8.0",
    },
    "bert_base": {
        "all_layers": [
            "embeddings",
            "encoder.layer.0.attention.self",
            "encoder.layer.0.attention.output.dense",
            "encoder.layer.0.attention.output.LayerNorm",
            "encoder.layer.0.intermediate.dense",
            "encoder.layer.0.output.dense",
            "encoder.layer.0.output.LayerNorm",
            "encoder.layer.1.attention.self",
            "encoder.layer.1.attention.output.dense",
            "encoder.layer.1.attention.output.LayerNorm",
            "encoder.layer.1.intermediate.dense",
            "encoder.layer.1.output.dense",
            "encoder.layer.1.output.LayerNorm",
            "encoder.layer.2.attention.self",
            "encoder.layer.2.attention.output.dense",
            "encoder.layer.2.attention.output.LayerNorm",
            "encoder.layer.2.intermediate.dense",
            "encoder.layer.2.output.dense",
            "encoder.layer.2.output.LayerNorm",
            "encoder.layer.3.attention.self",
            "encoder.layer.3.attention.output.dense",
            "encoder.layer.3.attention.output.LayerNorm",
            "encoder.layer.3.intermediate.dense",
            "encoder.layer.3.output.dense",
            "encoder.layer.3.output.LayerNorm",
            "encoder.layer.4.attention.self",
            "encoder.layer.4.attention.output.dense",
            "encoder.layer.4.attention.output.LayerNorm",
            "encoder.layer.4.intermediate.dense",
            "encoder.layer.4.output.dense",
            "encoder.layer.4.output.LayerNorm",
            "encoder.layer.5.attention.self",
            "encoder.layer.5.attention.output.dense",
            "encoder.layer.5.attention.output.LayerNorm",
            "encoder.layer.5.intermediate.dense",
            "encoder.layer.5.output.dense",
            "encoder.layer.5.output.LayerNorm",
            "encoder.layer.6.attention.self",
            "encoder.layer.6.attention.output.dense",
            "encoder.layer.6.attention.output.LayerNorm",
            "encoder.layer.6.intermediate.dense",
            "encoder.layer.6.output.dense",
            "encoder.layer.6.output.LayerNorm",
            "encoder.layer.7.attention.self",
            "encoder.layer.7.attention.output.dense",
            "encoder.layer.7.attention.output.LayerNorm",
            "encoder.layer.7.intermediate.dense",
            "encoder.layer.7.output.dense",
            "encoder.layer.7.output.LayerNorm",
            "encoder.layer.8.attention.self",
            "encoder.layer.8.attention.output.dense",
            "encoder.layer.8.attention.output.LayerNorm",
            "encoder.layer.8.intermediate.dense",
            "encoder.layer.8.output.dense",
            "encoder.layer.8.output.LayerNorm",
            "encoder.layer.9.attention.self",
            "encoder.layer.9.attention.output.dense",
            "encoder.layer.9.attention.output.LayerNorm",
            "encoder.layer.9.intermediate.dense",
            "encoder.layer.9.output.dense",
            "encoder.layer.9.output.LayerNorm",
            "encoder.layer.10.attention.self",
            "encoder.layer.10.attention.output.dense",
            "encoder.layer.10.attention.output.LayerNorm",
            "encoder.layer.10.intermediate.dense",
            "encoder.layer.10.output.dense",
            "encoder.layer.10.output.LayerNorm",
            "encoder.layer.11.attention.self",
            "encoder.layer.11.attention.output.dense",
            "encoder.layer.11.attention.output.LayerNorm",
            "encoder.layer.11.intermediate.dense",
            "encoder.layer.11.output.dense",
            "encoder.layer.11.output.LayerNorm",
            "pooler.dense",
        ],
        "conv_layers": [],  # BERT has no conv layers (transformer-only)
        "default_target_layer": "encoder.layer.11",
    },
    "gpt2": {
        "all_layers": [
            "wte",
            "wpe",
            "h.0.ln_1",
            "h.0.attn",
            "h.0.ln_2",
            "h.0.mlp.c_fc",
            "h.0.mlp.c_proj",
            "h.1.ln_1",
            "h.1.attn",
            "h.1.ln_2",
            "h.1.mlp.c_fc",
            "h.1.mlp.c_proj",
            "h.2.ln_1",
            "h.2.attn",
            "h.2.ln_2",
            "h.2.mlp.c_fc",
            "h.2.mlp.c_proj",
            "h.3.ln_1",
            "h.3.attn",
            "h.3.ln_2",
            "h.3.mlp.c_fc",
            "h.3.mlp.c_proj",
            "h.4.ln_1",
            "h.4.attn",
            "h.4.ln_2",
            "h.4.mlp.c_fc",
            "h.4.mlp.c_proj",
            "h.5.ln_1",
            "h.5.attn",
            "h.5.ln_2",
            "h.5.mlp.c_fc",
            "h.5.mlp.c_proj",
            "h.6.ln_1",
            "h.6.attn",
            "h.6.ln_2",
            "h.6.mlp.c_fc",
            "h.6.mlp.c_proj",
            "h.7.ln_1",
            "h.7.attn",
            "h.7.ln_2",
            "h.7.mlp.c_fc",
            "h.7.mlp.c_proj",
            "h.8.ln_1",
            "h.8.attn",
            "h.8.ln_2",
            "h.8.mlp.c_fc",
            "h.8.mlp.c_proj",
            "h.9.ln_1",
            "h.9.attn",
            "h.9.ln_2",
            "h.9.mlp.c_fc",
            "h.9.mlp.c_proj",
            "h.10.ln_1",
            "h.10.attn",
            "h.10.ln_2",
            "h.10.mlp.c_fc",
            "h.10.mlp.c_proj",
            "h.11.ln_1",
            "h.11.attn",
            "h.11.ln_2",
            "h.11.mlp.c_fc",
            "h.11.mlp.c_proj",
            "ln_f",
            "lm_head",
        ],
        "conv_layers": [],  # GPT-2 has no conv layers (transformer-only)
        "default_target_layer": "h.11",
    },
}


def get_static_layers(model_id: str) -> Dict[str, Any] | None:
    """
    Return pre-computed layer lists for a pretrained model.
    Used by the /layers endpoint for Grad-CAM target layer selection.
    Returns None if no static data is available (custom uploaded models).
    """
    data = _STATIC_LAYERS.get(model_id)
    if data is None:
        return None
    conv_layers = data["conv_layers"]
    return {
        "all_layers": data["all_layers"],
        "conv_layers": conv_layers,
        "recommended_layers": conv_layers[-5:] if conv_layers else [],
        "default_target_layer": data["default_target_layer"],
    }


__all__ = ["get_static_architecture", "has_static_architecture", "get_static_layers"]

# Made with Bob
